PRIORITY_SSID="team-14"
PRIORITY_PSK="123456789"
FALLBACK_SSIDS="NMT-Weblogin"
CAP_NMT_SSID="NMT-Weblogin"
CAP_NMT_LOGIN_URL="https://nmt-wireless.nmt.edu/cgi-bin/login"
CAP_NMT_USERNAME_FIELD="user"
CAP_NMT_PASSWORD_FIELD="password"
CAP_NMT_EXTRA_FIELDS="cmd=login&checkbox=on"
CAP_NMT_USERNAME="your_username"
CAP_NMT_PASSWORD="your_password"
SCAN_INTERVAL=15
CONNECT_TIMEOUT=20
INTERNET_CHECK_URL="http://clients3.google.com/generate_204"
