# Set base docker image
FROM ros:humble-ros-core AS base

# Create non-root user (luna) with access to full container
ARG USER=luna
# Base layer
RUN useradd -m $USER && usermod -aG dialout,video $USER \
    && apt-get update && apt-get install -y sudo git nano openssh-client rsync \
    && usermod -aG sudo $USER \
    && echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
    && rm -rf /var/lib/apt/lists/*

# Set default Docker settings
ENV HOME_DIR=/home/$USER
ENV WORKING_DIR=$HOME_DIR/NMT-Lunabotics2025-Python-based/system_operations
ENV HOST_FILES_DIR=/host_files  

# Set default shell to bash
SHELL ["/bin/bash", "-c"]

# Set USER back to root for package installation.
USER root 

FROM base AS core
RUN apt-get update && apt-get install -y \
    # Development packages:
    nano \
    git \
    x11-apps \
    usbutils \
    # Other
    build-essential \
    cmake \
    python3-pip \
    libeigen3-dev \
    python3-colcon-common-extensions \
    python3-rosdep \
    ros-humble-cv-bridge \
    ros-humble-image-transport \
    ros-humble-robot-state-publisher \
    ros-humble-joy \
    && rm -rf /var/lib/apt/lists/*

FROM core AS nav
RUN apt-get update && apt-get install -y \
    ros-humble-nav2-bringup \
    ros-humble-pcl-ros \
    ros-humble-rviz2 \
    ros-humble-rtabmap-ros \
    ros-humble-tf2-tools \
    && rm -rf /var/lib/apt/lists/*

FROM core AS sim
RUN apt-get update && apt-get install -y \
    ros-humble-turtlebot3* \
    #gazebo \
    #libgazebo-dev \
    #libboost-all-dev \
    && rm -rf /var/lib/apt/lists/*
    
FROM core AS python
RUN pip install --no-cache-dir \
    pyrealsense2 \
    pyudev \
    pyserial
    


FROM core AS final
#COPY --from=nav /opt/ros /opt/ros
#COPY --from=sim /opt/ros /opt/ros
#COPY --from=python /usr/local /usr/local


    



# Install ROS packages to install
USER $USER

#RUN mkdir -p $HOME_DIR/ros_ws/src && cd $HOME_DIR/ros_ws/src \
#    && cd $HOME_DIR/ros_ws \
#    && source /opt/ros/humble/setup.bash \
#    && rosdep update \
#    && colcon build

# Copy start_docker.sh into docker and make executable for accessing the container     && rosdep install --from-paths src --ignore-src -r -y \     #&& git clone https://github.com/hku-mars/FAST-LIVO2.git \
USER root
COPY start_docker.sh /usr/local/bin/start_docker
RUN chmod +x /usr/local/bin/start_docker \
    && echo "alias mystart='/usr/local/bin/start_docker'" >> /etc/bash.bashrc

# Create working directory for project
RUN mkdir -p $WORKING_DIR \
    && chown -R $USER:$USER $HOME_DIR

# Copy entrypoint.sh into container, make executable, and run to start the default robot behaviors
COPY entry_point.sh /entry_point.sh
RUN chmod +x /entry_point.sh
ENTRYPOINT ["/entry_point.sh"]

# Switch back to luna and set default working directory
USER $USER
WORKDIR $HOME_DIR