# Set base docker image
FROM ros:humble-ros-core

# Create non-root user (luna) with access to full container
ARG USER=luna
RUN useradd -m $USER && usermod -aG dialout,video $USER \
    && apt-get update && apt-get install -y sudo git nano openssh-client rsync \
    && usermod -aG sudo $USER \
    && echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
    && rm -rf /var/lib/apt/lists/*

# Set default Docker settings
ENV HOME_DIR=/home/$USER
ENV WORKING_DIR=$HOME_DIR/NMT-Lunabotics2025-Python-based/system_operations
ENV HOST_FILES_DIR=/host_files  

# Set default shell to bash
SHELL ["/bin/bash", "-c"]

# Set USER back to root for package installation.
USER root 

# System Packages to install
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y \
    #Essiental packages .ie fundamental compatibility packages that are required to run the robot
    #Development packages:
    nano \
    git \
    x11-apps \
    cmake \
    build-essential \
    libboost-all-dev \
    libeigen3-dev \
    python3-colcon-common-extensions \
    python3-pip \
    python3-rosdep \
    ros-humble-pcl-ros \
    ros-humble-cv-bridge \
    ros-humble-image-transport \
    ros-humble-nav2-bringup \
    ros-humble-rviz2 \
    && rm -rf /var/lib/apt/lists/*

#RUN rosdep init || true
#RUN rosdep update

# Install ROS packages to install
USER $USER

#RUN mkdir -p $HOME_DIR/ros_ws/src && cd $HOME_DIR/ros_ws/src \
#    && cd $HOME_DIR/ros_ws \
    #&& source /opt/ros/humble/setup.bash \
#    && rosdep update \
#    && colcon build

# Copy start_docker.sh into docker and make executable for accessing the container     && rosdep install --from-paths src --ignore-src -r -y \     #&& git clone https://github.com/hku-mars/FAST-LIVO2.git \
USER root
COPY start_docker.sh /usr/local/bin/start_docker
RUN chmod +x /usr/local/bin/start_docker \
    && echo "alias mystart='/usr/local/bin/start_docker'" >> /etc/bash.bashrc

# Create working directory for project
RUN mkdir -p $WORKING_DIR \
    && chown -R $USER:$USER $HOME_DIR

# Copy entrypoint.sh into container, make executable, and run to start the default robot behaviors
COPY entry_point.sh /entry_point.sh
RUN chmod +x /entry_point.sh
ENTRYPOINT ["/entry_point.sh"]

# Switch back to luna and set default working directory
USER $USER
WORKDIR $HOME_DIR
