# Set base docker image
FROM ros:humble-ros-core AS base

USER root

# Install apt-fast with pre-configuration to speed up apt-get operations
#RUN apt-get update && apt-get install -y --no-install-recommends \
#    software-properties-common \
#    aria2 \
#    && add-apt-repository -y ppa:apt-fast/stable \
#    && apt-get update \
#    && echo debconf apt-fast/maxdownloads string 10 | debconf-set-selections \
#    && echo debconf apt-fast/dlflag boolean true | debconf-set-selections \
#    && echo debconf apt-fast/aptmanager string apt-get | debconf-set-selections \
#    && DEBIAN_FRONTEND=noninteractive apt-get install -y apt-fast \
#    && apt-get clean \
#    && rm -rf /var/lib/apt/lists/*

# Set default shell to bash
SHELL ["/bin/bash", "-c"]

# Packages are setup as layers. A certain layer can be targeted for quick installs, only updated essential stuff
FROM base AS core
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    binutils \
    binutils-dev \
    cmake \
    python3-pip \
    python3-serial \
    libeigen3-dev \
    python3-colcon-common-extensions \
    python3-rosdep \
    ros-humble-cv-bridge \
    ros-humble-image-transport \
    ros-humble-robot-state-publisher \
    ros-humble-joy \
    ros-humble-rviz2 \
&& rm -rf /var/lib/apt/lists/*

# Create non-root user (luna) with access to full container
ARG USER=luna
# Base layer
RUN useradd -m $USER && usermod -aG dialout,video $USER \
    && apt-get update && apt-get install -y sudo git nano openssh-client rsync \
    && usermod -aG sudo $USER \
    && echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
    && rm -rf /var/lib/apt/lists/*

# Set default Docker settings
ENV HOME_DIR=/home/$USER
ENV WORKING_DIR=$HOME_DIR/NMT-Lunabotics2025-Python-based/system_operations
ENV HOST_FILES_DIR=/host_files 

# Core packages used to interact with docker system, (Not strictly needed)
FROM base AS dev
RUN apt-get update && apt-get install -y --no-install-recommends \
    nano \
    git \
    x11-apps \
    usbutils \
    v4l-utils \
 && rm -rf /var/lib/apt/lists/*

# Python packages needed to run system
FROM core AS python
RUN pip install --no-cache-dir \
    pyrealsense2 \
    pyudev 

# Packages used by docker to interact with sensors
FROM core AS sensors
RUN apt-get update && apt-get install -y \
    #ros-humble-usb-cam \
    ros-humble-v4l2-camera \
    ros-humble-compressed-image-transport \
    ros-humble-image-view \
    #pkg-config \
    #libusb-1.0-0-dev \
    #ros-humble-realsense2-camera \
&& rm -rf /var/lib/apt/lists/*
#ln -s /usr/include/libusb-1.0/libusb.h /usr/include/libusb.h

# Packages used for navigation in the system
FROM core AS nav
RUN apt-get update && apt-get install -y \
    ros-humble-slam-toolbox \
    #ros-humble-nav2-bringup \
    #ros-humble-pcl-ros \
    #ros-humble-rtabmap-ros \
    #ros-humble-tf2-tools \
&& rm -rf /var/lib/apt/lists/*

# Packages used for simulation
FROM core AS sim
RUN apt-get update && apt-get install -y \
    #gazebo \
    #ros-humble-turtlebot3* \
    #libgazebo-dev \
    #libboost-all-dev \
&& rm -rf /var/lib/apt/lists/*

FROM core AS final
COPY --from=dev / /    
COPY --from=python / /      
COPY --from=sensors / /      
COPY --from=nav / /         
COPY --from=sim / /       

# Install ROS packages to install
USER $USER

#RUN mkdir -p $HOME_DIR/ros_ws/src && cd $HOME_DIR/ros_ws/src \
#    && cd $HOME_DIR/ros_ws \
#    && source /opt/ros/humble/setup.bash \
#    && rosdep update \
#    && colcon build

# Copy start_docker.sh into docker and make executable for accessing the container     && rosdep install --from-paths src --ignore-src -r -y \     #&& git clone https://github.com/hku-mars/FAST-LIVO2.git \
USER root

COPY start_docker.sh /usr/local/bin/start_docker
RUN chmod +x /usr/local/bin/start_docker \
    && echo "alias mystart='/usr/local/bin/start_docker'" >> /etc/bash.bashrc

# Create working directory for project
RUN mkdir -p $WORKING_DIR \
    && chown -R $USER:$USER $HOME_DIR

# Copy entrypoint.sh into container, make executable, and run to start the default robot behaviors
COPY entry_point.sh /entry_point.sh
RUN chmod +x /entry_point.sh
ENTRYPOINT ["/entry_point.sh"]

# Switch back to luna and set default working directory
USER $USER
WORKDIR $HOME_DIR