<package format="3">
  <name>pi_camera</name>
  <version>0.0.1</version>
  <description>Pi camera node</description>
  <maintainer email="you@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>rclpy</exec_depend>
</package>
