<?xml version="1.0"?>
<package format="3">
  <name>pi_camera</name>
  <version>0.0.0</version>
  <description>Launch package for Raspberry Pi camera using v4l2_camera</description>
  <maintainer email="you@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>v4l2_camera</depend>
  <depend>image_transport</depend>
</package>
