cameras:
  - name: camera0
    video_device: /dev/video4 
    pixle_format: "YUYV"
    frame_rate: 60
    width: 848
    height: 480

  - name: camera1
    video_device: /dev/video10
    pixle_format: "YUYV"
    frame_rate: 24
    width: 80
    height: 60