cameras:
  - name: camera0
    video_device: /dev/video0
    frame_rate: 60
    width: 424
    height: 240

  - name: camera1
    video_device: /dev/video1
    frame_rate: 15
    width: 640
    height: 480