cameras:
  - name: camera0 # This camera should always be the overview camera 
    video_device: /dev/video4
    pixel_format: "AUTO"
    frame_rate: 15
    width: 424
    height: 240

  - name: camera1 # This camera should be the bucket camera
    video_device: /dev/video10
    pixel_format: "AUTO"
    frame_rate: 15
    width: 424
    height: 240

  - name: camera2 # This camera should be the bridge camera
    video_device: /dev/video16
    pixel_format: "AUTO"
    frame_rate: 15
    width: 424
    height: 240