cameras:
  - name: camera0 # This camera should always be the overview camera 
    video_device: /dev/video0 #/dev/v4l/by-id/usb-Intel_R__RealSense_TM__Depth_Camera_455_Intel_R__RealSense_TM__Depth_Camera_455-video-index0  #/dev/video4 
    pixel_format: "AUTO"
    frame_rate: 24
    width: 80
    height: 60

  - name: camera1 # This camera should be the bucket camera
    video_device: /dev/video6 #/dev/v4l/by-id/usb-Intel_R__RealSense_TM__Depth_Module_456_Intel_R__RealSense_TM__Depth_Module_456-video-index2 #/dev/video10
    pixel_format: "AUTO"
    frame_rate: 24
    width: 80
    height: 60

  - name: camera2 # This camera should be the bridge camera
    video_device: /dev/video15 #/dev/v4l/by-id/usb-Intel_R__RealSense_TM__Depth_Module_456_Intel_R__RealSense_TM__Depth_Module_456_311743060296-video-index2 #/dev/video16
    pixel_format: "AUTO"
    frame_rate: 24
    width: 80
    height: 60


#cameras:
#  - name: camera0 # This camera should always be the overview camera 
#    video_device: /dev/video4 #/dev/v4l/by-id/usb-Intel_R__RealSense_TM__Depth_Camera_455_Intel_R__RealSense_TM__Depth_Camera_455-video-index0  #/dev/video4 
#    pixel_format: "AUTO"
#    frame_rate: 24
#    width: 80
#    height: 60
#
#  - name: camera1 # This camera should be the bucket camera
#    video_device: /dev/video10 #/dev/v4l/by-id/usb-Intel_R__RealSense_TM__Depth_Module_456_Intel_R__RealSense_TM__Depth_Module_456-video-index2 #/dev/video10
#    pixel_format: "AUTO"
#    frame_rate: 24
#    width: 80
#    height: 60
#
#  - name: camera2 # This camera should be the bridge camera
#    video_device: /dev/video16 #/dev/v4l/by-id/usb-Intel_R__RealSense_TM__Depth_Module_456_Intel_R__RealSense_TM__Depth_Module_456_311743060296-video-index2 #/dev/video16
#    pixel_format: "AUTO"
#    frame_rate: 24
#    width: 80
#    height: 60