rgbd_odometry:
  ros__parameters:
    # Frames
    frame_id: "base_link"
    odom_frame_id: "odom"
    publish_tf: true

    # Topics
    rgb_image_topic: "/camera/camera/color/image_raw"
    depth_image_topic: "/camera/camera/aligned_depth_to_color/image_raw"
    camera_info_topic: "/camera/camera/color/camera_info"
    scan_topic: "/scan"
    imu_topic: "/camera/camera/gyro/sample"

    # Memory
    Mem/IncrementalMemory: "true"

    # Grid
    Grid/FromDepth: true
    Grid/3D: false
    Grid/CellSize: 0.05
    Grid/RangeMin: 0.3
    Grid/RangeMax: 5.0
    grid_map_publisher_rate: 1.0

    # Optional features
    visual_odometry: true
    approx_sync: true
    subscribe_depth: true
    subscribe_rgb: true
    subscribe_scan: true
