FROM python:3.11-slim AS builder

ARG USER=luna

# Create non-root user and install system dependencies
RUN useradd -m $USER && usermod -aG dialout,video $USER \
    && apt-get update && apt-get install -y sudo git nano curl rsync xz-utils udev \
    && echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
    && rm -rf /var/lib/apt/lists/*

# Set environment for the fake user
ENV HOME_DIR=/home/$USER
ENV WORKING_DIR=$HOME_DIR/NMT-Lunabotics2025-Python-based/system_operations
ENV PATH="/root/bin:${PATH}"

# Install Python packages
RUN pip install --no-cache-dir pyserial

# Install Arduino CLI
RUN curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh

# Switch to fake user
USER $USER
RUN mkdir -p $HOME_DIR/.arduino15 && chmod -R 777 $HOME_DIR/.arduino15 \
    && arduino-cli config init --config-file $HOME_DIR/.arduino15/arduino-cli.yaml \
    && arduino-cli core update-index \
    && arduino-cli core install arduino:avr \
    && arduino-cli core install arduino:renesas_uno

# Set working directory
WORKDIR $WORKING_DIR