controller_input_node:      
  ros__parameters:      
    automations:     
      A_BUTTON: dig
      B_BUTTON: none
      X_BUTTON: dump
      Y_BUTTON: none
      HORIZONTAL_DPAD_LEFT: auto_dig_1s
      HORIZONTAL_DPAD_RIGHT: none
      VERTICAL_DPAD_UP: none
      VERTICAL_DPAD_DOWN: auto_dump_1s